AllCops:
  Exclude:
    - vendor/**/*
    - examples/botspotting/**/*
    - examples/dm-bot/**/*
    - examples/downforeveryone-bot/**/*
    - examples/emoji-art-bot/**/*

#inherit_from: .rubocop_todo.yml
