source 'https://rubygems.org'
ruby '2.2.3'

gem 'dotenv'
gem 'json'
gem 'bing-search'
gem 'faye-websocket',           '0.10.2'
gem 'activesupport',            '4.2.5',      require: ['active_support/all']
gem 'slack-bot-manager'
gem 'redis'
